# Generated by Django 5.1.4 on 2024-12-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_balise_alter_issue_priority_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
